<?php
/**
 * @package	AcySMS for Joomla!
 * @version	3.1.0
 * @author	acyba.com
 * @copyright	(C) 2009-2016 ACYBA S.A.R.L. All rights reserved.
 * @license	GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 */
defined('_JEXEC') or die('Restricted access');
?><?php

class ACYSMSGateway_test_gateway extends ACYSMSGateway_default_gateway{

	public $errors = array();
	public $debug = false;
	public $name = 'Test';
	public $smsid = '';


	public function displayConfig(){

		echo JText::_('SMS_GATEWAY_TEST');
		echo '<br />';
		echo JText::sprintf('SMS_WAIT_TO_SEND', '<input type="text" style="width:20px;" name="data[senderprofile][senderprofile_params][waittosend]" id="senderprofile_waittosend" class="inputbox" value="'.intval($this->waittosend).'" />');
	}


	public function openSend($message, $phone){
		$num = rand(0, 50);
		if($num == 0){
			$this->errors[] = 'Random Connection error num 0 (Error generated by the test gateway)';
			return false;
		}
		if($num == 1){
			$this->errors[] = 'Random Connection error num 1 (Error generated by the test gateway)';
			return false;
		}

		return true;
	}

	public function closeSend($idConnection){
		$num = rand(0, 50);
		if($num == 0){
			$this->errors[] = 'Random error num 0 (Error generated by the test gateway)';
			return false;
		}
		if($num == 1){
			$this->errors[] = 'Random error num 1 (Error generated by the test gateway)';
			return false;
		}

		return true;
	}

}
